### ISSUE TITLE
Bytes improperly accepts references to string literals

### ISSUE THREAD

**Issue by cxw42** [tobyink/p5-types-encodings#1]
With Perl 5.26.1, Ubuntu 18.04.2 x64, Type::Tiny 1.004004, Types::Standard 1.004004, Type::Utils 1.004004, Types::Encodings 0.002, `Bytes` works fine on string literals:

    $ perl -MTypes::Encodings=Bytes -E 'Types::Encodings::Bytes->assert_valid("foo\x{26a0}")'
    Value "foo\x{26a0}" did not pass type constraint "Bytes" at -e line 1

But when I pass a reference to the string instead (and want to reject it):

    $ perl -MTypes::Encodings=Bytes -E 'Types::Encodings::Bytes->assert_valid(\"foo\x{26a0}")'
    $

No error message!  This despite the fact that parent `Types::Encodings::Str` correctly rejects references:

    $ perl -MTypes::Encodings=Bytes,Str -E 'Types::Encodings::Str->assert_valid(\"foo\x{26a0}")'
    Reference \"foo\x{26a0}" did not pass type constraint "Str" at -e line 1

What say you?  Thank you for looking into this!

**Edit** I tried replacing the `inline_as` code with the sample from the Type::Utils POD, and it works in my use case:

    declare Bytes,
	as Str,
	where     { !utf8::is_utf8($_) },
    #inline_as { "!utf8::is_utf8($_)" };
    inline_as {
      my ($constraint, $varname) = @_;
      my $perlcode =
         $constraint->parent->inline_check($varname)
         . "&& (!utf8::is_utf8($varname))";
      return $perlcode;
    };

(I also, first, tried replacing `""` with `''` in the `inline_as` string, but that didn't work.)

**Comment by cxw42** [comment]
By the way, I can submit a PR for this in October if you'd like ;)

**Comment by tobyink** [comment]
Fixed in 0.003.

**Comment by cxw42** [comment]
Thank you!  Works fine in my use cases.
