### ISSUE TITLE
Bytes improperly accepts undef

### ISSUE THREAD

**Issue by cxw42** [tobyink/p5-types-encodings#2]
Same test conditions as #1:

    $ perl -MTypes::Encodings=Bytes,Str -E 'Types::Encodings::Str->assert_valid(undef)'
    Undef did not pass type constraint "Str" at -e line 1
       ...
    $ perl -MTypes::Encodings=Bytes,Str -E 'Types::Encodings::Bytes->assert_valid(undef)'
    # No error message - oops!
    $ 

**Edit** The possible fix in #1 solves this issue as well.

**Comment by tobyink** [comment]
Fixed in 0.003.
